# Generated by Django 5.0.14 on 2026-02-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0009_enforce_company_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
